# Generated by Django 2.2 on 2020-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='Airbags',
            field=models.CharField(choices=[('&#9989;', 'Yes'), ('&#10060;', 'No')], default='No', max_length=32),
        ),
    ]
