# Generated by Django 2.2 on 2020-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200216_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='desc',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postdesc',
            field=models.TextField(default='Nothing', max_length=500),
        ),
    ]
